### PR TITLE
Update README instructions

### PR DESCRIPTION
**Pull request by C47D**
Based in #79

### CODE REVIEW

**Comment by an-erd** [comment]
In PR #79 the EXTRA_COMPONENT_DIRS needs to be a single line or split using "\\"

**Comment by C47D** [comment]
@an-erd did you meant like that?

**Comment by an-erd** [comment]
Yes, that works for the makefile.

**Comment by C47D** [comment]
Hi @an-erd, 

I've just updated the README, so now instead of creating a directory named `externals` now it's named `components`. I've tested both CMake and Makefiles and had no success.

With the CMake approach I had the following error:
image

With the Makefile approch the menuconfig appeared but I didn't find the new menues were they should be.

Can you test the Makefile approach on your side to check if it works, I'm sure I'm doing something wrong...

Regards
Carlos

**Comment by C47D** [comment]
@an-erd Nevermind, i found the issues and now everything seems to be working as expected :)

**Pull request merged**
