### PR TITLE
Support for ft6x36 capacitive touch screen controller

### PR DESCRIPTION
**Pull request by seeul8er**
- Added support for ft6x36 and potentially ft6x06 touch screen controllers. Tested with ER-TFTM035-6 display module (ILI9488 & FT6236)
- Added config options
- Added notice in README

### CODE REVIEW

**Comment by embeddedt** [comment]
@C47D I think you're much more familiar with this code than I am.

**Comment by C47D** [comment]
I can take a look at it later today or @jeremyjh if he's available.

**Comment by C47D** [comment]
Did a quick glance at the code and it seems to be ready to merge, i don't have the display to test it tho.

I would abstract the touch interface like we did at `disp_driver` abstracting the diferent display controllers but that can be done after the proposed new directory structure at #49.

What do you think @seeul8er, @kisvegabor, @embeddedt, @jeremyjh?

**Comment by kisvegabor** [comment]
I also couldn't test it but look good to me too.

> I would abstract the touch interface like we did at disp_driver abstracting the diferent display controllers but that can be done after the proposed new directory structure at #49.

That would be great!

**Comment by kisvegabor** [comment]
@C47D My proposal still stands about adding write access to you or @jeremyjh if you are interested. :slightly_smiling_face:

**Comment by C47D** [comment]
Thanks for the proposal @kisvegabor, now I have less work at my day job so I can accept having write access in the repo. Hope @jeremyjh can also accept.

**Comment by kisvegabor** [comment]
Awesome, thank you! 
I've set the invitation.

**Comment by C47D** [comment]
Thanks, I've just accepted it.

**Pull request merged**
